// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// IMPORTANT: This middleware only runs on the CLIENT side. It attaches the
// bearer token to outgoing server function requests, but it does NOT perform
// any server-side authentication or validation.
//
// Server functions that require authentication must independently apply the
// `requireSupabaseAuth` middleware in their `.middleware()` chain. Relying on
// this middleware alone does NOT protect server functions from unauthenticated
// access.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const { data } = await supabase.auth.getSession()
    const token = data.session?.access_token
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
